version: 0.2

phases:
  build:
    commands:
      - echo "Running updateSongInfo function"
      - grep "script.js" index.html

artifacts:
  files:
    - index.html   # Incluye el archivo index.html generado en el artefacto
  discard-paths: yes


